<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('carriers', function (Blueprint $table) {
            $table->increments('id');
            $table->char('name',100);
            $table->char('code',50);
            $table->timestamps();
        });

        $this->seedCarriers();
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('carriers');
    }

    public function  seedCarriers(){
        $carriers = array(
            ['name' => 'DHL Express', 'code' => 'dhl'],
            ['name' => 'UPS', 'code' => 'ups'],
            ['name' => 'Fedex', 'code' => 'fedex'],
            ['name' => 'TNT', 'code' => 'tnt'],
            ['name' => 'China EMS', 'code' => 'china-ems'],
            ['name' => 'China Post', 'code' => 'china-post'],
            ['name' => 'Singapore Post', 'code' => 'singapore-post'],
            ['name' => 'Singapore Speedpost', 'code' => 'singapore-speedpost'],
            ['name' => 'Hong Kong Post', 'code' => 'hong-kong-post'],
            ['name' => 'Swiss Post', 'code' => 'swiss-post'],
            ['name' => 'USPS', 'code' => 'usps'],
            ['name' => 'UK Royal Mail', 'code' => 'royal-mail'],
            ['name' => 'Parcel Force', 'code' => 'parcel-force'],
            ['name' => 'PostNL International', 'code' => 'postnl-parcels'],
            ['name' => 'Netherlands Post', 'code' => 'netherlands-post'],
            ['name' => 'Australia Post', 'code' => 'australia-post'],
            ['name' => 'Australia EMS', 'code' => 'australia-ems'],
            ['name' => 'Canada Post', 'code' => 'canada-post'],
            ['name' => 'New Zealand Post', 'code' => 'new-zealand-post'],
            ['name' => 'Bpost', 'code' => 'belgium-post'],
            ['name' => 'Brazil Correios', 'code' => 'brazil-correios'],
            ['name' => 'Russian Post', 'code' => 'russian-post'],
            ['name' => 'Sweden Posten', 'code' => 'sweden-posten'],
            ['name' => 'La Poste', 'code' => 'laposte'],
            ['name' => 'France EMS - Chronopost', 'code' => 'chronopost'],
            ['name' => 'Colissimo', 'code' => 'colissimo'],
            ['name' => 'Poste Italiane', 'code' => 'poste-italiane'],
            ['name' => 'India Post', 'code' => 'india-post'],
            ['name' => 'Magyar Posta', 'code' => 'magyar-posta'],
            ['name' => 'YANWEN', 'code' => 'yanwen'],
            ['name' => 'DHL Germany', 'code' => 'dhl-germany'],
            ['name' => 'An Post', 'code' => 'an-post'],
            ['name' => 'DHL Parcel NL', 'code' => 'dhlparcel-nl'],
            ['name' => 'DHL Poland Domestic', 'code' => 'dhl-poland'],
            ['name' => 'DHL Spain Domestic', 'code' => 'dhl-es'],
            ['name' => 'Mexico Post', 'code' => 'correos-mexico'],
            ['name' => 'Posten Norge', 'code' => 'posten-norge'],
            ['name' => 'TNT Italy', 'code' => 'tnt-it'],
            ['name' => 'TNT France', 'code' => 'tnt-fr'],
            ['name' => 'Portugal Post - CTT', 'code' => 'ctt'],
            ['name' => 'South African Post Office', 'code' => 'south-africa-post'],
            ['name' => 'Correos Spain', 'code' => 'correos-spain'],
            ['name' => 'Chunghwa POST', 'code' => 'taiwan-post'],
            ['name' => 'Ukraine Post', 'code' => 'ukraine-post'],
            ['name' => 'Ukraine EMS', 'code' => 'ukraine-ems'],
            ['name' => 'Emirates Post', 'code' => 'emirates-post'],
            ['name' => 'Uruguay Post', 'code' => 'uruguay-post'],
            ['name' => 'Japan Post', 'code' => 'japan-post'],
            ['name' => 'Romania Post', 'code' => 'posta-romana'],
            ['name' => 'Korea Post', 'code' => 'korea-post'],
            ['name' => 'ELTA Hellenic Post', 'code' => 'greece-post'],
            ['name' => 'Deutsche Post', 'code' => 'deutsche-post'],
            ['name' => 'Czech Post', 'code' => 'czech-post'],
            ['name' => 'Correos Chile', 'code' => 'correos-chile'],
            ['name' => 'Aland Post', 'code' => 'aland-post'],
            ['name' => 'Macao Post', 'code' => 'macao-post'],
            ['name' => 'WishPost', 'code' => 'wishpost'],
            ['name' => 'PFC Express', 'code' => 'pfcexpress'],
            ['name' => 'Yun Express', 'code' => 'yunexpress'],
            ['name' => 'CNE Express', 'code' => 'cnexps'],
            ['name' => 'Buylogic', 'code' => 'buylogic'],
            ['name' => '4PX', 'code' => '4px'],
            ['name' => 'Anjun Logistics', 'code' => 'anjun'],
            ['name' => 'J-NET Express', 'code' => 'j-net'],
            ['name' => 'Miuson Express', 'code' => 'miuson-international'],
            ['name' => 'SF International Small Packet', 'code' => 'sfb2c'],
            ['name' => 'Domestic SF Express', 'code' => 'sf-express'],
            ['name' => 'STO Express', 'code' => 'sto'],
            ['name' => 'YTO Express', 'code' => 'yto'],
            ['name' => 'TTKD Express', 'code' => 'ttkd'],
            ['name' => 'JD Express', 'code' => 'jd'],
            ['name' => 'ZTO Express', 'code' => 'zto'],
            ['name' => 'ZJS International', 'code' => 'zjs-express'],
            ['name' => 'Yunda Express', 'code' => 'yunda'],
            ['name' => 'DEPPON', 'code' => 'deppon'],
            ['name' => 'XQ Express', 'code' => 'xqwl'],
            ['name' => 'Chukou1 Logistics', 'code' => 'chukou1'],
            ['name' => 'XRU', 'code' => 'xru'],
            ['name' => 'Ruston', 'code' => 'ruston'],
            ['name' => 'QFKD Express', 'code' => 'qfkd'],
            ['name' => 'Nanjing Woyuan', 'code' => 'nanjingwoyuan'],
            ['name' => 'Hua Han Logistics', 'code' => 'hhexp'],
            ['name' => 'Flyt Express', 'code' => 'flytexpress'],
            ['name' => 'Ali Business Logistics', 'code' => 'al8856'],
            ['name' => 'JCEX', 'code' => 'jcex'],
            ['name' => 'DPE Express', 'code' => 'dpe-express'],
            ['name' => 'LWE', 'code' => 'lwehk'],
            ['name' => 'Equick China', 'code' => 'equick-cn'],
            ['name' => 'DWZ Express', 'code' => 'dwz'],
            ['name' => 'Takesend Logistics', 'code' => 'takesend'],
            ['name' => 'AliExpress Standard Shipping', 'code' => 'global'],
            ['name' => 'Global Cainiao', 'code' => 'cainiao'],
            ['name' => 'TGX', 'code' => 'tgx'],
            ['name' => '1DL Express', 'code' => '1dlexpress'],
            ['name' => 'iMile', 'code' => 'imile'],
            ['name' => 'Ausworld Express', 'code' => 'aus'],
            ['name' => 'SX-Express', 'code' => 'sxexpress'],
            ['name' => 'Tracknator', 'code' => 'tracknator'],
            ['name' => 'UVAN Express', 'code' => 'uvan'],
            ['name' => 'CSD Express', 'code' => 'csd'],
            ['name' => 'Sri Lanka Post', 'code' => 'sri-lanka-post'],
            ['name' => 'EWE Global Express', 'code' => 'ewe'],
            ['name' => 'ECMS Express', 'code' => 'ecms'],
            ['name' => 'Sudan Post', 'code' => 'sudan-post'],
            ['name' => 'DEX-I', 'code' => 'dex-i'],
            ['name' => 'Nippon Express', 'code' => 'nippon'],
            ['name' => 'COSCO eGlobal', 'code' => 'cosco'],
            ['name' => 'CDEK Turkey', 'code' => 'cdek-tr'],
            ['name' => 'WEL', 'code' => 'logistics'],
            ['name' => 'Spee-Dee Delivery', 'code' => 'speedee'],
            ['name' => 'Syrian Post', 'code' => 'syrian-post'],
            ['name' => 'RaidereX', 'code' => 'raiderex'],
            ['name' => 'allekurier', 'code' => 'allekurier'],
            ['name' => 'GuangChi Express', 'code' => 'guangchi'],
            ['name' => 'LP Express', 'code' => 'lpexpress'],
            ['name' => 'Un-line', 'code' => 'un-line'],
            ['name' => 'RZY Express', 'code' => 'rzyexpress'],
            ['name' => 'Transrush', 'code' => 'transrush'],
            ['name' => 'Venipak', 'code' => 'venipak'],
            ['name' => 'Tanzania Post', 'code' => 'tanzania-post'],
            ['name' => 'Suteng Logistics', 'code' => 'ste56'],
            ['name' => 'BAB international', 'code' => 'bab-ru'],
            ['name' => 'Thailand Post', 'code' => 'thailand-post'],
            ['name' => 'Airpak Express', 'code' => 'airpak-express'],
            ['name' => 'Winit', 'code' => 'winit'],
            ['name' => 'Togo Post', 'code' => 'togo-post'],
            ['name' => 'QEXPRESS', 'code' => 'qexpress'],
            ['name' => 'CNILINK', 'code' => 'cnilink'],
            ['name' => 'Szendex', 'code' => 'szendex'],
            ['name' => 'Joying Box', 'code' => 'joying-box'],
            ['name' => 'Tonga Post', 'code' => 'tonga-post'],
            ['name' => 'LBC Express', 'code' => 'lbcexpress'],
            ['name' => '360zebra', 'code' => '360zebra'],
            ['name' => 'Spoton Logistics', 'code' => 'spoton'],
            ['name' => 'Smartcat', 'code' => 'tcat-cn'],
            ['name' => 'Chinz Logistics', 'code' => 'chinz56'],
            ['name' => 'HKD', 'code' => 'hkdexpress'],
            ['name' => 'Tunisia Post', 'code' => 'tunisia-post'],
            ['name' => 'Pandu Logistics', 'code' => 'pandulogistics'],
            ['name' => 'Auexpress', 'code' => 'auexpress'],
            ['name' => 'Dachser', 'code' => 'dachser'],
            ['name' => 'Pitney Bowes', 'code' => 'pitneybowes'],
            ['name' => 'Turkey Post', 'code' => 'turkey-post'],
            ['name' => 'DPD(HK)', 'code' => 'dpd-hk'],
            ['name' => '99minutos', 'code' => '99minutos'],
            ['name' => 'FedEx UK', 'code' => 'fedex-uk'],
            ['name' => 'TopYou', 'code' => 'topyou'],
            ['name' => 'DPD Belgium', 'code' => 'dpd-be'],
            ['name' => 'Tuvalu Post', 'code' => 'tuvalu-post'],
            ['name' => 'Uganda Post', 'code' => 'uganda-post'],
            ['name' => 'Collect+', 'code' => 'collectplus'],
            ['name' => 'Zhongtie Logistics', 'code' => 'ztky'],
            ['name' => 'SAP Express', 'code' => 'sap-express'],
            ['name' => 'Shopee Express SPX PH', 'code' => 'spx-ph'],
            ['name' => 'TNT Click', 'code' => 'tnt-click'],
            ['name' => 'Skynet Worldwide Express UK', 'code' => 'skynetworldwide-uk'],
            ['name' => 'Dada logistic', 'code' => 'idada56'],
            ['name' => 'Showl', 'code' => 'showl'],
            ['name' => 'V-Xpress', 'code' => 'v-xpress'],
            ['name' => 'Rufengda', 'code' => 'rufengda'],
            ['name' => 'Hermesworld', 'code' => 'hermes'],
            ['name' => 'Jersey Post', 'code' => 'jersey-post'],
            ['name' => 'Sendle', 'code' => 'sendle'],
            ['name' => 'WSE Logistics', 'code' => 'gdwse'],
            ['name' => 'DHL Parcel UK', 'code' => 'dhl-uk'],
            ['name' => 'Maxway Logistics', 'code' => 'maxway'],
            ['name' => 'Comet Hellas', 'code' => 'comethellas'],
            ['name' => 'Nightline', 'code' => 'nightline'],
            ['name' => 'Bombino Express', 'code' => 'bombino-express'],
            ['name' => 'KINGRUNS', 'code' => 'kingruns'],
            ['name' => 'TONGDA Global', 'code' => 'tarrive'],
            ['name' => 'MailAmericas', 'code' => 'mailamericas'],
            ['name' => 'Ninja Van Malaysia', 'code' => 'ninjavan-my'],
            ['name' => 'JT Express MY', 'code' => 'jtexpress-my'],
            ['name' => 'Uzbekistan Post', 'code' => 'uzbekistan-post'],
            ['name' => 'APC Postal Logistics', 'code' => 'apc'],
            ['name' => 'Lexship', 'code' => 'lexship'],
            ['name' => 'Uzbekistan EMS', 'code' => 'uzbekistan-ems'],
            ['name' => 'Far International Logistics', 'code' => 'far800'],
            ['name' => 'Whistl', 'code' => 'whistl'],
            ['name' => 'XYL 816Kapro', 'code' => '816kf'],
            ['name' => 'Vanuatu Post', 'code' => 'vanuatu-post'],
            ['name' => 'Newgistics', 'code' => 'newgistics'],
            ['name' => 'DHL Netherlands', 'code' => 'dhl-nl'],
            ['name' => 'Ninja Van Indonesia', 'code' => 'ninjaxpress'],
            ['name' => 'OrangeDS', 'code' => 'orangeds'],
            ['name' => 'DX Delivery', 'code' => 'dxdelivery'],
            ['name' => 'Redpack Mexico', 'code' => 'redpack-mexico'],
            ['name' => 'Easy Ship', 'code' => 'easyship'],
            ['name' => 'Old Dominion Freight Line', 'code' => 'old-dominion'],
            ['name' => 'Roadbull Logistics', 'code' => 'roadbull'],
            ['name' => 'Ninja Van Philippines', 'code' => 'ninjavan-ph'],
            ['name' => 'Vietnam Post', 'code' => 'vietnam-post'],
            ['name' => 'DHL Benelux', 'code' => 'dhl-benelux'],
            ['name' => 'Hui Logistics', 'code' => 'huilogistics'],
            ['name' => 'Post One', 'code' => 'postone'],
            ['name' => 'Estes', 'code' => 'estes'],
            ['name' => 'Ninja Van Thailand', 'code' => 'ninjavan-th'],
            ['name' => 'ChangJiang Express', 'code' => 'changjiangexpress'],
            ['name' => 'Yemen Post', 'code' => 'yemen-post'],
            ['name' => 'SuperOZ Logistics', 'code' => 'superoz'],
            ['name' => 'Bee Express', 'code' => 'bee'],
            ['name' => 'Zambia Post', 'code' => 'zambia-post'],
            ['name' => 'Sai Cheng Logistics', 'code' => 'saicheng'],
            ['name' => 'Leopards Express', 'code' => 'leopardschina'],
            ['name' => 'CSE', 'code' => 'cse'],
            ['name' => 'Zimbabwe Post', 'code' => 'zimbabwe-post'],
            ['name' => 'Beebird Logistics', 'code' => 'beebird'],
            ['name' => 'FBA ES Swiship', 'code' => 'swiship-es'],
            ['name' => 'Greyhound', 'code' => 'greyhound'],
            ['name' => '8Europe', 'code' => '8europe'],
            ['name' => 'FirstMile', 'code' => 'firstmile'],
            ['name' => 'Overseas Logistics', 'code' => 'overseas-logistics'],
            ['name' => 'Royal Shipments', 'code' => 'royal-shipments'],
            ['name' => 'YuTeng Worldwide', 'code' => 'yuteng'],
            ['name' => 'Globegistics Inc.', 'code' => 'globegistics'],
            ['name' => 'Dellin', 'code' => 'dellin'],
            ['name' => 'Better Express', 'code' => 'cbtsd'],
            ['name' => 'SYD Express', 'code' => 'suyd56'],
            ['name' => 'Bluecare Express', 'code' => 'bluecare'],
            ['name' => 'Nexive', 'code' => 'nexive'],
            ['name' => 'Tk Kit', 'code' => 'tk-kit'],
            ['name' => 'Asendia HK', 'code' => 'asendia-hk'],
            ['name' => 'Linex', 'code' => 'linexsolutions'],
            ['name' => 'intelcom', 'code' => 'intelcom'],
            ['name' => 'Overnite Express', 'code' => 'overnitenet'],
            ['name' => 'Airwings Courier Express India', 'code' => 'airwings-india'],
            ['name' => 'Loomis Express', 'code' => 'loomis'],
            ['name' => 'Hermes Germany', 'code' => 'hermes-de'],
            ['name' => 'JT Express TH', 'code' => 'jt-express-th'],
            ['name' => 'The Professional Couriers (TPC)', 'code' => 'professional-couriers'],
            ['name' => 'ESNAD Express', 'code' => 'esnad'],
            ['name' => 'International Seur', 'code' => 'international-seur'],
            ['name' => 'ABF Freight', 'code' => 'abf'],
            ['name' => 'ASM', 'code' => 'asmred'],
            ['name' => 'Shopee Express SPX ID', 'code' => 'spx-id'],
            ['name' => 'P2P TrakPak', 'code' => 'trakpak'],
            ['name' => 'XingYunYi', 'code' => 'xingyunyi'],
            ['name' => 'TNT LT', 'code' => 'tnt-lt'],
            ['name' => 'Matkahuolto', 'code' => 'matkahuolto'],
            ['name' => 'Couriers Please express', 'code' => 'couriers-please'],
            ['name' => 'ACS Courier', 'code' => 'acscourier'],
            ['name' => 'LJS', 'code' => 'bt-exp'],
            ['name' => 'DHL France', 'code' => 'dhl-fr'],
            ['name' => 'RL Carriers', 'code' => 'rl-carriers'],
            ['name' => 'ShipEntegra', 'code' => 'shipentegra'],
            ['name' => 'Afghan Post', 'code' => 'afghan-post'],
            ['name' => 'DPD Poland', 'code' => 'dpd-poland'],
            ['name' => 'AsiaFly', 'code' => 'asiafly'],
            ['name' => 'GLS PL', 'code' => 'gls-pl'],
            ['name' => 'Albania Post', 'code' => 'posta-shqiptare'],
            ['name' => 'cititrans', 'code' => 'cititrans'],
            ['name' => 'Geniki Taxydromiki', 'code' => 'taxydromiki'],
            ['name' => 'Cess', 'code' => 'cess'],
            ['name' => 'PostaPlus', 'code' => 'postaplus'],
            ['name' => 'Andorra Post', 'code' => 'andorra-post'],
            ['name' => 'Envialia', 'code' => 'envialia'],
            ['name' => 'Best Express', 'code' => 'bestex'],
            ['name' => '1SD', 'code' => '1shida'],
            ['name' => 'Amazon IN', 'code' => 'amazon-in'],
            ['name' => 'Canpar Courier', 'code' => 'canpar'],
            ['name' => 'Flying Leopards Express', 'code' => 'njfeibao'],
            ['name' => 'Amazon UK', 'code' => 'amazon-uk'],
            ['name' => 'CBL Logistics', 'code' => 'cbl-logistica'],
            ['name' => 'First Flight Couriers', 'code' => 'firstflightme'],
            ['name' => 'VNCPost', 'code' => 'vncpost'],
            ['name' => 'JET Express', 'code' => 'jet'],
            ['name' => 'Redur Spain', 'code' => 'redur-es'],
            ['name' => 'Antilles Post', 'code' => 'antilles-post'],
            ['name' => 'Argentina Post', 'code' => 'correo-argentino'],
            ['name' => 'Siodemka', 'code' => 'siodemka'],
            ['name' => '360lion Express', 'code' => '360lion'],
            ['name' => 'ZTO International', 'code' => 'zto-international'],
            ['name' => 'Armenia Post', 'code' => 'armenia-post'],
            ['name' => 'Aruba Post', 'code' => 'aruba-post'],
            ['name' => 'DPD France', 'code' => 'exapaq'],
            ['name' => 'HCT Express', 'code' => 'hct'],
            ['name' => 'LDXpress', 'code' => 'ldxpress'],
            ['name' => 'Spring GDS', 'code' => 'spring-gds'],
            ['name' => 'Austrian Post', 'code' => 'austria-post'],
            ['name' => 'Azerbaijan Post', 'code' => 'azerbaijan-post'],
            ['name' => 'CJ Logistics', 'code' => 'doortodoor'],
            ['name' => 'TCS Express', 'code' => 'tcs-express'],
            ['name' => 'Bahrain Post', 'code' => 'bahrain-post'],
            ['name' => 'K1 Express', 'code' => 'kuajingyihao'],
            ['name' => 'VOVA Logistics', 'code' => 'vova-logistics'],
            ['name' => 'JT Express VN', 'code' => 'jt-express'],
            ['name' => 'Bangladesh EMS', 'code' => 'bangladesh-ems'],
            ['name' => '7-ELEVEN', 'code' => 'qi-eleven'],
            ['name' => 'Barbados Post', 'code' => 'barbados-post'],
            ['name' => 'Belarus Post', 'code' => 'belpochta'],
            ['name' => 'ORANGE CONNEX', 'code' => 'orangeconnex'],
            ['name' => 'CTT Express', 'code' => 'ctt-express'],
            ['name' => 'Belize Post', 'code' => 'belize-post'],
            ['name' => 'Benin Post', 'code' => 'benin-post'],
            ['name' => 'GLS Netherland', 'code' => 'gls-nl'],
            ['name' => 'Bermuda Post', 'code' => 'bermuda-post'],
            ['name' => 'JS EXPRESS', 'code' => 'js-exp'],
            ['name' => 'We World Express', 'code' => 'weworld-express'],
            ['name' => 'Bhutan Post', 'code' => 'bhutan-post'],
            ['name' => 'Bolivia Post', 'code' => 'correos-bolivia'],
            ['name' => 'Gofly', 'code' => 'gofly'],
            ['name' => 'Bosnia And Herzegovina Post', 'code' => 'bosnia-and-herzegovina-post'],
            ['name' => 'Gao Post', 'code' => 'gaopost'],
            ['name' => 'Shopee Express SPX VN', 'code' => 'spx-vn'],
            ['name' => 'Botswana Post', 'code' => 'botswana-post'],
            ['name' => 'Shopee Express SPX MY', 'code' => 'spx-my'],
            ['name' => 'Brunei Post', 'code' => 'brunei-post'],
            ['name' => 'DB Schenker', 'code' => 'dbschenker'],
            ['name' => 'Bulgaria Post', 'code' => 'bulgaria-post'],
            ['name' => 'JINDOUYUN Logistics', 'code' => 'jdy'],
            ['name' => 'Burkina Faso Post', 'code' => 'sonapost'],
            ['name' => 'UK Mail', 'code' => 'ukmail'],
            ['name' => 'Burundi Post', 'code' => 'burundi-post'],
            ['name' => 'SINOAIR', 'code' => 'sinoair'],
            ['name' => 'ZHONGSU International', 'code' => 'zhongsu'],
            ['name' => 'Cambodia Post', 'code' => 'cambodia-post'],
            ['name' => 'Detrack', 'code' => 'detrack'],
            ['name' => 'UK Asendia', 'code' => 'uktracking-asendia'],
            ['name' => 'Cameroon Post', 'code' => 'campost'],
            ['name' => 'Italy SDA', 'code' => 'italy-sda'],
            ['name' => 'Asendia UK Premium', 'code' => 'asendia-wmp'],
            ['name' => 'Correios Cabo Verde', 'code' => 'correios-cabo-verde'],
            ['name' => 'Palletways', 'code' => 'palletways'],
            ['name' => 'T Cat', 'code' => 't-cat'],
            ['name' => 'Eshipping', 'code' => 'yht'],
            ['name' => 'Fastway South Africa', 'code' => 'fastway-za'],
            ['name' => 'Fastgo', 'code' => 'fastgo'],
            ['name' => 'MyIB', 'code' => 'myib'],
            ['name' => 'Colombia Post', 'code' => 'colombia-post'],
            ['name' => 'Delcart', 'code' => 'delcart-in'],
            ['name' => 'Weaship', 'code' => 'weaship'],
            ['name' => 'PCA', 'code' => 'pca'],
            ['name' => 'Fulfillmen', 'code' => 'fulfillmen'],
            ['name' => 'GTI', 'code' => 'gti'],
            ['name' => 'City-Link Express', 'code' => 'citylinkexpress'],
            ['name' => 'FTD Express', 'code' => 'ftd'],
            ['name' => 'tuffnells', 'code' => 'tuffnells'],
            ['name' => '2GO', 'code' => '2go'],
            ['name' => 'Parcel Freight Logistics', 'code' => 'pflogistics'],
            ['name' => 'Shipgce Express', 'code' => 'shipgce'],
            ['name' => 'Croatia Post', 'code' => 'hrvatska-posta'],
            ['name' => 'Xend Express', 'code' => 'xend'],
            ['name' => 'Exelot', 'code' => 'exelot'],
            ['name' => 'Cuba Post', 'code' => 'cuba-post'],
            ['name' => 'Wise Express', 'code' => 'wise-express'],
            ['name' => 'Sure56', 'code' => 'sure56'],
            ['name' => 'CEVA Logistics', 'code' => 'ceva-logistics'],
            ['name' => 'Cyprus Post', 'code' => 'cyprus-post'],
            ['name' => 'AIR21', 'code' => 'air21'],
            ['name' => 'GATI Courier', 'code' => 'gaticn'],
            ['name' => 'Cnpex', 'code' => 'cnpex'],
            ['name' => 'UBX Express', 'code' => 'ubx-uk'],
            ['name' => 'JT Express CN', 'code' => 'jtexpress'],
            ['name' => 'Denmark post', 'code' => 'denmark-post'],
            ['name' => 'Airspeed International Corporation', 'code' => 'airspeed'],
            ['name' => 'DPEX China', 'code' => 'szdpex'],
            ['name' => '1hcang', 'code' => '1hcang'],
            ['name' => 'Shree Mahabali Express', 'code' => 'shree-mahabali-express'],
            ['name' => 'Sailpost', 'code' => 'sailpost'],
            ['name' => 'RAF Philippines', 'code' => 'raf'],
            ['name' => 'Asyad Express', 'code' => 'asyad'],
            ['name' => 'Dominican Post', 'code' => 'inposdom'],
            ['name' => 'YDH', 'code' => 'ydhex'],
            ['name' => 'Tiki', 'code' => 'tiki'],
            ['name' => 'Ecuador Post', 'code' => 'correos-del-ecuador'],
            ['name' => 'Sunyou', 'code' => 'sunyou'],
            ['name' => 'QuicKway', 'code' => 'quickway'],
            ['name' => 'Egypt Post', 'code' => 'egypt-post'],
            ['name' => 'Wahana', 'code' => 'wahana'],
            ['name' => 'Janio Asia', 'code' => 'janio'],
            ['name' => 'El Salvador Post', 'code' => 'el-salvador-post'],
            ['name' => 'DHL Global Mail Asia', 'code' => 'dhlecommerce-asia'],
            ['name' => 'Giao Hàng Nhanh', 'code' => 'ghn'],
            ['name' => 'Kerry Express TH', 'code' => 'kerryexpress-th'],
            ['name' => 'Eritrea Post', 'code' => 'eritrea-post'],
            ['name' => 'DHL Active Tracing', 'code' => 'dhl-active'],
            ['name' => 'Border Express', 'code' => 'border-express'],
            ['name' => 'Estonia Post', 'code' => 'omniva'],
            ['name' => 'Viettel Post', 'code' => 'viettelpost'],
            ['name' => 'TT Sucha', 'code' => 'twth'],
            ['name' => 'Ethiopia Post', 'code' => 'ethiopia-post'],
            ['name' => 'TNT Reference', 'code' => 'tnt-reference'],
            ['name' => 'YL express', 'code' => 'yunlu'],
            ['name' => 'Faroe Islands Post', 'code' => 'faroe-islands-post'],
            ['name' => 'Dotzot', 'code' => 'dotzot'],
            ['name' => 'Kerry eCommerce', 'code' => 'kerry-ecommerce'],
            ['name' => 'Fiji Post', 'code' => 'fiji-post'],
            ['name' => 'Kangaroo Worldwide Express', 'code' => 'kangaroo-my'],
            ['name' => 'NZCouriers', 'code' => 'nzcouriers'],
            ['name' => 'Finland Post - Posti', 'code' => 'finland-posti'],
            ['name' => 'Jiayi Express', 'code' => 'jiayi56'],
            ['name' => 'Kerry Express VN', 'code' => 'kerryexpress'],
            ['name' => 'Hermes Borderguru', 'code' => 'hermes-borderguru'],
            ['name' => 'Deltec Courier', 'code' => 'deltec-courier'],
            ['name' => 'GEL Express', 'code' => 'gel-express'],
            ['name' => 'Maxcellents Pte Ltd', 'code' => 'maxcellents'],
            ['name' => 'Shipa', 'code' => 'shipa'],
            ['name' => 'Nationwide Express', 'code' => 'nationwide-my'],
            ['name' => 'Buffalo', 'code' => 'buffaloex'],
            ['name' => 'Post Haste', 'code' => 'posthaste'],
            ['name' => 'Georgia Post', 'code' => 'georgian-post'],
            ['name' => 'RPX Online', 'code' => 'rpxonline'],
            ['name' => 'Score Jp', 'code' => 'scorejp'],
            ['name' => 'Flash Express', 'code' => 'flashexpress'],
            ['name' => 'Ghana Post', 'code' => 'ghana-post'],
            ['name' => 'Gibraltar  Post', 'code' => 'gibraltar-post'],
            ['name' => 'Nhans Solutions', 'code' => 'nhans-solutions'],
            ['name' => 'LD Logistics', 'code' => 'ldlog'],
            ['name' => 'SCG Express', 'code' => 'scg-express'],
            ['name' => 'Espeedpost', 'code' => 'espeedpost'],
            ['name' => 'Greenland Post', 'code' => 'tele-post'],
            ['name' => 'Jet-Ship Worldwide', 'code' => 'jet-ship'],
            ['name' => 'XPOST', 'code' => 'xpost'],
            ['name' => 'GLS Spain', 'code' => 'gls-es'],
            ['name' => 'GmbH', 'code' => 'myaustrianpost'],
            ['name' => 'FBA UK Swiship', 'code' => 'swiship-uk'],
            ['name' => 'Guatemala Post', 'code' => 'elcorreo'],
            ['name' => 'Ecargo', 'code' => 'ecargo-asia'],
            ['name' => 'Guernsey Post', 'code' => 'guernsey-post'],
            ['name' => 'Delhivery', 'code' => 'delhivery'],
            ['name' => 'Cosex', 'code' => 'cosex'],
            ['name' => 'Amazon FBA Swiship', 'code' => 'swiship-usa'],
            ['name' => 'GLS', 'code' => 'gls'],
            ['name' => 'BRT Bartolini', 'code' => 'bartolini'],
            ['name' => 'ETS Express', 'code' => 'ets-express'],
            ['name' => 'Hong Tai', 'code' => 'ht56'],
            ['name' => 'CGS Express', 'code' => 'cgs-express'],
            ['name' => 'DPD', 'code' => 'dpd'],
            ['name' => 'Comet Hellas', 'code' => 'cometcourier'],
            ['name' => 'E-lian', 'code' => 'elianpost'],
            ['name' => 'Aramex', 'code' => 'aramex'],
            ['name' => 'TOLL', 'code' => 'toll'],
            ['name' => 'Ecom Express', 'code' => 'ecom-express'],
            ['name' => 'Quantium', 'code' => 'quantium'],
            ['name' => 'Bao Tongda Freight Forwarding', 'code' => 'btd56'],
            ['name' => 'Day & Ross', 'code' => 'dayross'],
            ['name' => 'Iceland Post', 'code' => 'iceland-post'],
            ['name' => 'GDEX', 'code' => 'gdex'],
            ['name' => 'Alpha Fast', 'code' => 'alpha-fast'],
            ['name' => 'Shree Maruti Courier', 'code' => 'shreemaruticourier'],
            ['name' => 'TForce Final Mile', 'code' => 'tforce'],
            ['name' => 'Omni Parcel', 'code' => 'omniparcel'],
            ['name' => 'Indonesia Post', 'code' => 'indonesia-post'],
            ['name' => 'SkyNet Malaysia', 'code' => 'skynet'],
            ['name' => 'CDEK Express', 'code' => 'cdek'],
            ['name' => 'BQC', 'code' => 'bqc'],
            ['name' => 'Iran Post', 'code' => 'iran-post'],
            ['name' => 'Trackon Courier', 'code' => 'trackon'],
            ['name' => 'JT Express PH', 'code' => 'jtexpress-ph'],
            ['name' => 'Hnfywl', 'code' => 'hnfywl'],
            ['name' => 'CND Express', 'code' => 'cndexpress'],
            ['name' => 'Israel Post', 'code' => 'israel-post'],
            ['name' => 'JoeyCo', 'code' => 'joeyco'],
            ['name' => 'Netherland Post - PostNL', 'code' => 'postnl-3s'],
            ['name' => 'OCS Express', 'code' => 'ocschina'],
            ['name' => 'Kerry Tec', 'code' => 'kerry-tec'],
            ['name' => 'Packeta', 'code' => 'packeta'],
            ['name' => 'Ivory Coast EMS', 'code' => 'ivory-coast-ems'],
            ['name' => 'Naqel', 'code' => 'naqel'],
            ['name' => 'BEL', 'code' => '8256ru'],
            ['name' => 'Jamaica Post', 'code' => 'jamaica-post'],
            ['name' => 'Paquet Express', 'code' => 'paquet'],
            ['name' => 'Pitney Bowes', 'code' => 'parcel'],
            ['name' => 'CXC', 'code' => 'cxc'],
            ['name' => 'Jordan Post', 'code' => 'jordan-post'],
            ['name' => 'One World Express', 'code' => 'oneworldexpress'],
            ['name' => 'GOGO Xpress', 'code' => 'gogo-xpress'],
            ['name' => 'Kazakhstan Post', 'code' => 'kazpost'],
            ['name' => 'ADSOne', 'code' => 'adsone'],
            ['name' => 'BSI express', 'code' => 'bsi'],
            ['name' => 'Amazon Logistics', 'code' => 'amazon'],
            ['name' => 'etower', 'code' => 'etower'],
            ['name' => 'Kenya Post', 'code' => 'kenya-post'],
            ['name' => 'Landmark Global', 'code' => 'landmark-global'],
            ['name' => 'Airfex', 'code' => 'airfex'],
            ['name' => 'The Courier Guy', 'code' => 'thecourierguy'],
            ['name' => 'King Kong Express', 'code' => 'kke'],
            ['name' => 'YiYuan', 'code' => 'yiyuan'],
            ['name' => 'SMSA Express', 'code' => 'smsa-express'],
            ['name' => 'Best Express(logistic)', 'code' => '800best'],
            ['name' => 'BEST Express (Malaysia)', 'code' => 'best-my'],
            ['name' => 'Cosmetics Now', 'code' => 'costmeticsnow'],
            ['name' => 'Kyrgyzstan Post', 'code' => 'kyrgyzpost'],
            ['name' => 'SFC Service', 'code' => 'sfcservice'],
            ['name' => 'Laos Post', 'code' => 'laos-post'],
            ['name' => 'Latvia Post', 'code' => 'latvijas-pasts'],
            ['name' => 'EC-Firstclass', 'code' => 'ec-firstclass'],
            ['name' => 'YJI', 'code' => 'yji'],
            ['name' => 'Cubyn', 'code' => 'cubyn'],
            ['name' => 'Lebanon Post', 'code' => 'liban-post'],
            ['name' => 'MyHermes UK', 'code' => 'hermes-uk'],
            ['name' => 'Hi Life', 'code' => 'hi-life'],
            ['name' => 'Lesotho Post', 'code' => 'lesotho-post'],
            ['name' => 'DHL ECommerce', 'code' => 'dhlglobalmail'],
            ['name' => 'WeDo Logistics', 'code' => 'wedo'],
            ['name' => 'SpeedPAK', 'code' => 'speedpak'],
            ['name' => 'DPD UK', 'code' => 'dpd-uk'],
            ['name' => 'Geodis', 'code' => 'geodis'],
            ['name' => 'TNT UK', 'code' => 'tnt-uk'],
            ['name' => 'Zajil', 'code' => 'zajil'],
            ['name' => 'anxl', 'code' => 'anxl'],
            ['name' => 'Liechtenstein Post', 'code' => 'liechtenstein-post'],
            ['name' => 'Ltexp', 'code' => 'ltexp'],
            ['name' => '华航吉运', 'code' => 'hlihang-express'],
            ['name' => 'Lithuania Post', 'code' => 'lietuvos-pastas'],
            ['name' => 'Lazada (LEX)', 'code' => 'lgs'],
            ['name' => 'CJ Packet', 'code' => 'cj-dropshipping'],
            ['name' => 'Hlihang Express', 'code' => 'hlihang-express'],
            ['name' => 'Luxembourg Post', 'code' => 'luxembourg-post'],
            ['name' => 'GLS Italy', 'code' => 'gls-italy'],
            ['name' => 'InPost Paczkomaty', 'code' => 'inpost-paczkomaty'],
            ['name' => 'Jayeek', 'code' => 'jayeek'],
            ['name' => 'DSV', 'code' => 'dsv'],
            ['name' => 'StarTrack', 'code' => 'star-track'],
            ['name' => 'Dekun', 'code' => 'dekun'],
            ['name' => '17Feia Express', 'code' => '17feia'],
            ['name' => 'Zeleris', 'code' => 'zeleris'],
            ['name' => 'Macedonia Post', 'code' => 'macedonia-post'],
            ['name' => 'Echo', 'code' => 'echo'],
            ['name' => 'Blue Sky Express', 'code' => 'blueskyexpress'],
            ['name' => 'DPD Ireland', 'code' => 'dpd-ireland'],
            ['name' => 'EMPS Express', 'code' => 'empsexpress'],
            ['name' => 'YMDD', 'code' => 'yimidida'],
            ['name' => 'DHL Global Forwarding', 'code' => 'dhl-global-logistics'],
            ['name' => 'Toll IPEC', 'code' => 'toll-ipec'],
            ['name' => 'OnTrac', 'code' => 'ontrac'],
            ['name' => 'PosLaju', 'code' => 'poslaju'],
            ['name' => 'Malaysia Post', 'code' => 'malaysia-post'],
            ['name' => 'Asendia USA', 'code' => 'asendia-usa'],
            ['name' => 'ECPOST', 'code' => 'ecpost'],
            ['name' => 'Aprche', 'code' => 'aprche'],
            ['name' => 'DAO365', 'code' => 'dao365'],
            ['name' => 'Maldives Post', 'code' => 'maldives-post'],
            ['name' => 'Asendia UK', 'code' => 'asendia-uk'],
            ['name' => 'Cacesa Postal', 'code' => 'cacesapostal'],
            ['name' => 'TAQBIN Malaysia', 'code' => 'taqbin-my'],
            ['name' => 'Yodel', 'code' => 'yodel'],
            ['name' => 'CRE', 'code' => 'cre'],
            ['name' => 'Xing Yuan', 'code' => 'xingyuan'],
            ['name' => 'Estafeta', 'code' => 'estafeta'],
            ['name' => 'Malta Post', 'code' => 'malta-post'],
            ['name' => 'Asendia Germany', 'code' => 'asendia-de'],
            ['name' => 'Ekart Logistics', 'code' => 'ekart'],
            ['name' => 'Bonds Couriers', 'code' => 'bondscouriers'],
            ['name' => 'Famiport', 'code' => 'famiport'],
            ['name' => 'Yong Man Yi', 'code' => 'ymy'],
            ['name' => 'Kerry Logistics', 'code' => 'kerry-logistics'],
            ['name' => 'Shree Tirupati Courier', 'code' => 'shree-tirupati'],
            ['name' => 'Mauritius Post', 'code' => 'mauritius-post'],
            ['name' => 'CourierPost', 'code' => 'courierpost'],
            ['name' => 'Taiwan Pelican Express', 'code' => 'e-can'],
            ['name' => 'Pushpak Courier', 'code' => 'pushpak-courier'],
            ['name' => 'Safexpress', 'code' => 'safexpress'],
            ['name' => 'Meest Express', 'code' => 'meest'],
            ['name' => 'Moldova Post', 'code' => 'moldova-post'],
            ['name' => 'Purolator', 'code' => 'purolator'],
            ['name' => 'ACOMMERCE', 'code' => 'acommerce'],
            ['name' => 'Pony Express', 'code' => 'pony-express'],
            ['name' => 'Shree Nandan Courier', 'code' => 'shree-nandan'],
            ['name' => 'Monaco Post', 'code' => 'la-poste-monaco'],
            ['name' => 'IML Logistics', 'code' => 'imlb2c'],
            ['name' => '139 ECONOMIC Package', 'code' => '139express'],
            ['name' => 'HiveWMS', 'code' => 'hivewms'],
            ['name' => 'Madhur Couriers', 'code' => 'madhur-couriers'],
            ['name' => 'Monaco EMS', 'code' => 'monaco-ems'],
            ['name' => 'Boxc Logistics', 'code' => 'boxc'],
            ['name' => 'Mongol Post', 'code' => 'mongol-post'],
            ['name' => 'UBI Smart Parcel', 'code' => 'ubi-logistics'],
            ['name' => 'Bombax', 'code' => 'bombax'],
            ['name' => 'Montenegro Post', 'code' => 'posta-crne-gore'],
            ['name' => 'Fastway New Zealand', 'code' => 'fastway-nz'],
            ['name' => 'Ltian', 'code' => 'ltian'],
            ['name' => 'Maroc Poste', 'code' => 'poste-maroc'],
            ['name' => 'DPEX', 'code' => 'dpex'],
            ['name' => 'Fastway Australia', 'code' => 'fastway-au'],
            ['name' => 'Shadowfax', 'code' => 'shadowfax'],
            ['name' => 'Fastway Ireland', 'code' => 'fastway-ie'],
            ['name' => 'SJTSZ Express', 'code' => 'sjtsz'],
            ['name' => 'MRW', 'code' => 'mrw-spain'],
            ['name' => 'Usky', 'code' => 'uskyexpress'],
            ['name' => 'International EMS', 'code' => 'ems-post'],
            ['name' => 'Namibia Post', 'code' => 'namibia-post'],
            ['name' => 'Come One express', 'code' => 'com1express'],
            ['name' => 'Packlink', 'code' => 'packlink'],
            ['name' => 'KUAYUE EXPRESS', 'code' => 'kye'],
            ['name' => 'Ark express', 'code' => 'arkexpress'],
            ['name' => 'UPU', 'code' => 'upu'],
            ['name' => 'Arrow XL', 'code' => 'arrowxl'],
            ['name' => 'I-parcel', 'code' => 'i-parcel'],
            ['name' => 'Colis Prive', 'code' => 'colis-prive'],
            ['name' => 'Winlink logistics', 'code' => 'winlink'],
            ['name' => 'MC Express', 'code' => 'md-express'],
            ['name' => 'Bluedart', 'code' => 'bluedart'],
            ['name' => 'LaserShip', 'code' => 'lasership'],
            ['name' => 'Fast Express', 'code' => 'kjkd'],
            ['name' => 'China Russia56', 'code' => 'china-russia56'],
            ['name' => 'New Caledonia Post', 'code' => 'new-caledonia-post'],
            ['name' => 'DTDC', 'code' => 'dtdc'],
            ['name' => 'xpresspost', 'code' => 'xpresspost'],
            ['name' => 'Grand Slam Express', 'code' => 'grandslamexpress'],
            ['name' => 'Nicaragua Post', 'code' => 'nicaragua-post'],
            ['name' => 'GoJavas', 'code' => 'gojavas'],
            ['name' => 'Fetchr', 'code' => 'fetchr'],
            ['name' => 'FedEx Poland Domestic', 'code' => 'opek'],
            ['name' => 'XDP Express', 'code' => 'xdp-uk'],
            ['name' => 'EFSPost', 'code' => 'efspost'],
            ['name' => 'ePacket', 'code' => 'epacket'],
            ['name' => 'LiBang International Logistics', 'code' => 'lbexps'],
            ['name' => 'Chit Chats', 'code' => 'chitchats'],
            ['name' => 'Nigeria Post', 'code' => 'nigeria-post'],
            ['name' => 'First Flight', 'code' => 'first-flight'],
            ['name' => 'Ledii', 'code' => 'ledii'],
            ['name' => 'SkyNet Worldwide Express', 'code' => 'skynetworldwide'],
            ['name' => 'SGT Corriere Espresso', 'code' => 'sgt-it'],
            ['name' => 'Eyou800', 'code' => 'eyoupost'],
            ['name' => 'eTotal', 'code' => 'etotal'],
            ['name' => 'Top Ideal Express', 'code' => 'zhuozhi'],
            ['name' => 'Gati-KWE', 'code' => 'gati-kwe'],
            ['name' => 'IMEX Global Solutions', 'code' => 'imexglobalsolutions'],
            ['name' => 'TCI Express', 'code' => 'tci'],
            ['name' => 'Oman Post', 'code' => 'oman-post'],
            ['name' => 'KGM Hub', 'code' => 'kgmhub'],
            ['name' => 'Easy Mail', 'code' => 'easy-mail'],
            ['name' => 'Qxpress', 'code' => 'qxpress'],
            ['name' => 'IDEX', 'code' => 'idexpress'],
            ['name' => 'FD Express', 'code' => 'fd-express'],
            ['name' => 'DTDC Plus', 'code' => 'dtdc-plus'],
            ['name' => 'hound', 'code' => 'hound'],
            ['name' => 'OCS Worldwide', 'code' => 'ocs-worldwide'],
            ['name' => 'ROSAN EXPRESS', 'code' => 'rosan'],
            ['name' => 'RR Donnelley', 'code' => 'rrdonnelley'],
            ['name' => 'WSGD Logistics', 'code' => 'wsgd-logistics'],
            ['name' => 'Con-way Freight', 'code' => 'con-way'],
            ['name' => 'Fedex Freight', 'code' => 'fedex-freight'],
            ['name' => 'UEQ', 'code' => 'ueq'],
            ['name' => 'Estafeta USA', 'code' => 'estafetausa'],
            ['name' => 'Ninja Van Singapore', 'code' => 'ninjavan'],
            ['name' => 'ESHUN International Logistics', 'code' => 'zes-express'],
            ['name' => 'SRE Korea', 'code' => 'srekorea'],
            ['name' => 'Speedex Courier', 'code' => 'speedexcourier'],
            ['name' => 'FedEx Ground', 'code' => 'fedex-ground'],
            ['name' => 'Sum Xpress', 'code' => 'sumxpress'],
            ['name' => 'Art Logexpress', 'code' => 'artlogexpress'],
            ['name' => 'Overseas Territory FR EMS', 'code' => 'overseas-territory-fr-ems'],
            ['name' => 'Expeditors', 'code' => 'expeditors'],
            ['name' => 'utec', 'code' => 'utec'],
            ['name' => 'GLS US', 'code' => 'gls-us'],
            ['name' => 'Yamato Japan', 'code' => 'taqbin-jp'],
            ['name' => 'SPSR', 'code' => 'spsr'],
            ['name' => 'DHL Hong Kong', 'code' => 'dhl-hong-kong'],
            ['name' => 'eParcel Korea', 'code' => 'eparcel-kr'],
            ['name' => 'Trending Times', 'code' => 'deltafille'],
            ['name' => 'Chronopost Portugal', 'code' => 'chronopost-portugal'],
            ['name' => 'Flyway Express', 'code' => 'flywayex'],
            ['name' => 'FUJIE Express', 'code' => 'fujexp'],
            ['name' => 'Sagawa', 'code' => 'sagawa'],
            ['name' => 'UPS Freight', 'code' => 'ups-freight'],
            ['name' => 'SUNING', 'code' => 'suning'],
            ['name' => 'DD Express', 'code' => 'ddexpress'],
            ['name' => 'XpressBees', 'code' => 'xpressbees'],
            ['name' => 'XDEXPRESS', 'code' => 'xdexpress'],
            ['name' => 'Express One', 'code' => 'expressone'],
            ['name' => 'ABX Express', 'code' => 'abxexpress-my'],
            ['name' => 'Courier IT', 'code' => 'courier-it'],
            ['name' => 'UPS Ground', 'code' => 'ups-ground'],
            ['name' => 'DPD Germany', 'code' => 'dpd-de'],
            ['name' => 'DPD Romania', 'code' => 'dpd-ro'],
            ['name' => 'Specialised Freight', 'code' => 'specialised-freight'],
            ['name' => 'venucia', 'code' => 'qichen'],
            ['name' => 'CARIBOU', 'code' => 'caribou'],
            ['name' => 'Overseas Territory US Post', 'code' => 'overseas-territory-us-post'],
            ['name' => 'Mypostonline', 'code' => 'mypostonline'],
            ['name' => 'UPS Mail Innovations', 'code' => 'ups-mi'],
            ['name' => 'RRS Logistics', 'code' => 'rrs'],
            ['name' => 'Pakistan Post', 'code' => 'pakistan-post'],
            ['name' => '13ten', 'code' => '13-ten'],
            ['name' => 'SKY Postal', 'code' => 'sky-postal'],
            ['name' => 'Jam Express', 'code' => 'jam-express'],
            ['name' => 'DPE South Africa', 'code' => 'dpe-south-africa'],
            ['name' => 'Saia LTL Freight', 'code' => 'saia-freight'],
            ['name' => 'Dawn Wing', 'code' => 'dawn-wing'],
            ['name' => '138sd', 'code' => '138sd'],
            ['name' => 'Hanxuan international express', 'code' => 'hxgj56'],
            ['name' => 'Panama Post', 'code' => 'correos-panama'],
            ['name' => 'Jayon Express (JEX)', 'code' => 'jayonexpress'],
            ['name' => 'Fastrak Services', 'code' => 'fastrak-services'],
            ['name' => 'Papua New Guinea Post', 'code' => 'postpng'],
            ['name' => 'Nova Poshta', 'code' => 'nova-poshta'],
            ['name' => 'KWT Express', 'code' => 'kwt56'],
            ['name' => 'Auspost', 'code' => 'auspost'],
            ['name' => 'Paraguay Post', 'code' => 'correo-paraguayo'],
            ['name' => 'RPX Indonesia', 'code' => 'rpx'],
            ['name' => 'Antron Express', 'code' => '168express'],
            ['name' => 'Serpost', 'code' => 'serpost'],
            ['name' => 'Philippines Post', 'code' => 'phlpost'],
            ['name' => 'SGT Express', 'code' => 'sgtwl'],
            ['name' => 'Correos Express', 'code' => 'correosexpress'],
            ['name' => 'Poland Post', 'code' => 'poczta-polska'],
            ['name' => 'FAST BEE', 'code' => 'fbb'],
            ['name' => 'Qatar Post', 'code' => 'qatar-post'],
            ['name' => 'Wiseloads', 'code' => 'wiseloads'],
            ['name' => 'COE', 'code' => 'coe'],
            ['name' => 'UC Express', 'code' => 'uc-express'],
            ['name' => 'wnDirect', 'code' => 'wndirect'],
            ['name' => 'ELTA Courier', 'code' => 'elta-courier-gr'],
            ['name' => 'Rwanda Post', 'code' => 'iposita-rwanda'],
            ['name' => 'Eurodis', 'code' => 'eurodis'],
            ['name' => 'TIPSA', 'code' => 'tip-sa'],
            ['name' => 'Saint Lucia Post', 'code' => 'saint-lucia-post'],
            ['name' => 'Matdespatch', 'code' => 'matdespatch'],
            ['name' => 'LHT Express', 'code' => 'lhtex'],
            ['name' => 'Saint Vincent And The Grenadines', 'code' => 'svgpost'],
            ['name' => 'Samoa Post', 'code' => 'samoa-post'],
            ['name' => 'TNT Australia', 'code' => 'tnt-au'],
            ['name' => 'Wanb Express', 'code' => 'wanbexpress'],
            ['name' => 'AnserX', 'code' => 'anserx'],
            ['name' => 'San Marino Post', 'code' => 'san-marino-post'],
            ['name' => 'SprintPack', 'code' => 'sprintpack'],
            ['name' => 'KJY Logistics', 'code' => 'kjy'],
            ['name' => 'yakit', 'code' => 'yakit'],
            ['name' => 'CHOICE Logistics', 'code' => 'choice'],
            ['name' => 'Saudi Post', 'code' => 'saudi-post'],
            ['name' => 'Kawa', 'code' => 'kawa'],
            ['name' => 'Hunter Express', 'code' => 'hunterexpress'],
            ['name' => 'JD Logistics', 'code' => 'jd-logistics'],
            ['name' => 'Senegal Post', 'code' => 'senegal-post'],
            ['name' => 'Serbia Post', 'code' => 'serbia-post'],
            ['name' => 'TAQBIN Hong Kong', 'code' => 'taqbin-hk'],
            ['name' => 'Line Clear Express & Logistics', 'code' => 'line-clear'],
            ['name' => 'Seychelles Post', 'code' => 'seychelles-post'],
            ['name' => 'Speed Post', 'code' => 'speed-post'],
            ['name' => 'UBon Express', 'code' => 'ubonex'],
            ['name' => 'Euasia Express', 'code' => 'euasia'],
            ['name' => 'OCA Argentina', 'code' => 'oca-ar'],
            ['name' => 'EWS Profit Fields', 'code' => '8dt'],
            ['name' => 'Asendia', 'code' => 'asendia'],
            ['name' => 'SEINO', 'code' => 'seino'],
            ['name' => 'Slovakia Post', 'code' => 'slovakia-post'],
            ['name' => 'Slovenia Post', 'code' => 'slovenia-post'],
            ['name' => '2U Express', 'code' => '2uex'],
            ['name' => 'IEPost', 'code' => 'iepost'],
            ['name' => 'Espost', 'code' => 'espost'],
            ['name' => 'Solomon Post', 'code' => 'solomon-post'],
            ['name' => 'Ane Express', 'code' => 'ane66'],
            ['name' => 'Alljoy', 'code' => 'alljoy'],
            ['name' => 'Echindia', 'code' => 'global-routers'],
            ['name' => 'JT Express SG', 'code' => 'jt-express-sg'],
            ['name' => 'Huida Express', 'code' => 'huidaex'],
            ['name' => 'A PLUS EXPRESS', 'code' => 'aplus100'],
        );

        DB::table('carriers')->insert($carriers);
    }
};
